// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    lottery_sc
    (
        init => init
        joinLottery => join_lottery
        extractWinners => extract_winners
        claimReward => claim_reward
        getIsLotteryOpen => is_lottery_open
        getAllParticipants => participants
        getIsWinner => is_winner
        wrongEndpoint => wrong_endpoint
        joinLotteryV2 => join_lottery_v2
        claimRewardV2 => claim_reward_v2
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
