// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    multi_token_contract
    (
        init => init
        deposit => deposit
        withdraw => withdraw
        balanceOfBatch => balance_of_batch
        setApprovalForAll => set_approval_for_all
        safeTransferFrom => safe_transfer_from
        safeBatchTransferFrom => safe_batch_transfer_from
        mint => mint
        mintBatch => mint_batch
        burn => burn
        burnBatch => burn_batch
        isApprovedForAll => approved_for_all
        balanceOf => balance
        enableContract => enable_contract
        disableContract => disable_contract
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
