// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           24
// Async Callback:                       1
// Total number of exported functions:  26

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    subscription_contract
    (
        init => init
        deposit => deposit
        withdraw => withdraw
        subscribe => subscribe
        unsubscribe => unsubscribe
        getAllUsers => all_users
        getSubscribedServices => subscribed_services
        getBalance => balance
        getBalanceTokenIds => balance_token_ids
        getWhitelistedTokenIds => whitelisted_token_ids
        getEnabled => enabled
        getServiceProviders => service_providers
        getAdminServiceProvider => admin_service_provider
        getServices => services
        getLastClaimedSubscriptionFee => last_claimed_subscription_fee
        enableContract => enable_contract
        disableContract => disable_contract
        whitelistTokenIds => whitelist_token_ids
        removeTokenIds => remove_token_ids
        addPairAddresses => add_pair_addresses
        claimSubscriptionFee => claim_subscription_fee
        registerServiceProvider => register_service_provider
        addServices => add_services
        replaceServices => replace_services
        removeServices => remove_services
    )
}

multiversx_sc_wasm_adapter::async_callback! { subscription_contract }
